meta_product_name: "TURMA"
meta_title: "TURMA - Your digital tourmanager"
meta_description: "TURMA helps you to have all your important information in one place. Retreive, Update and Communciate. Streamline your touring experience with TURMA - yoru digital tour manager!"
meta_image: "cover.png" # should exist in `app/assets/images/`
